export const SECTOR_FILTER_VALUES = [
  "Energy",
  "Environment",
  "Government",
  "Aerospace & defence",
  "Manufacturing",
  "Retail",
  "Financial services",
  "Support services",
  "Information Technology",
  "Healthcare",
  "Food & agriculture",
  "Automotive",
  "Tourism & hospitality",
  "Construction",
  "Security",
  "Transport",
  "Water",
  "Media & entertainment",
]